version: '3.3'
services:
    mariadb:
        container_name: mariadb
        ports:
            - '3306:3306'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        image: mariadb