# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ISLab Blockchain - IslabTracer

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, islab-tracer]

    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/Tracer-Backend
            git pull origin develop
            pm2 delete all
            npm run deploy
