# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ISLab Blockchain - IslabTracer

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, islab-tracer]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Source Update
        run: git pull

      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Module Install - npm install
        run: npm install

      - name: Build - npm build
        run: npm run build
