# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ISLab Blockchain - IslabTracer

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, islab-tracer-backend]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Source Update
        run: git pull

      - name: Module Install - npm install
        run: npm ci

      - name: Build - npm build
        run: npm run build

      - name: Process Clean
        run: pm2 delete all

      - name: Process Start
        run: pm2 start ./deploy.json
